"""Add verified column

Revision ID: 441137fd1e7a
Revises: 3113bdfc32ca
Create Date: 2018-02-15 20:04:26.098749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '441137fd1e7a'
down_revision = '3113bdfc32ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('verified', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'verified')
    # ### end Alembic commands ###
